skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_mint = "JCy7VmaXAS28emJPFNTr8qjvT7BrXXnAs26his91vnhX"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
